### PR TITLE
Fix build and add CI

### PR DESCRIPTION
**Pull request by paulb777**
Fix SPM build issues and add CI for future regression testing

Screenshot 2023-10-23 at 4 07 59 PM

### CODE REVIEW

**Comment by paulb777** [comment]
@sampajano Would appreciate your team's review, merge, and 1.49.2 tag to fix the SPM build issues. And also to carry the fixes and CI forward to future releases.

cc: @ncooke3 @wu-hui

**Comment by sampajano** [comment]
@paulb777 Thanks for filing the issue!

I suppose this was the same one we've been discussion? i.e. regarding `use_frameworks`?

**Comment by paulb777** [comment]
@sampajano No, this is different. `use_frameworks!` is a CocoaPods issue. This PR fixes the Swift Package Manager build and adds CI to help keep it working.

**Comment by sampajano** [comment]
@paulb777 Oh! Sorry i didn't look closely!

Thanks so much for adding the CI for us!!

This looks great!

@HannahShiSFB PTAL too!

**Review by sampajano — APPROVED** [review]
Thanks so much for the new CI!

@HannahShiSFB PTAL — i suppose this fills in some holes which we have today. If we have more similar holes (i.e. build tests), we should fill them too. Thanks!

**Pull request merged**
